[book]
title = "San Andreas Penal Codes"
description = "Laws and ordinances governing the state of San Andreas, Bone County, and Las Venturas."
language = "en"
authors = [
  "Standal",
  "AVine96",
  "Wildbm",
  "Awucard"
]
