name: Build & Deploy Site

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1.1.13

      - name: Build Documentation
        run: mdbook build

      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          folder: book
